# Generated by Django 3.2.25 on 2024-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransactionmodel',
            old_name='current_amount',
            new_name='from_bank_current_amount',
        ),
        migrations.AddField(
            model_name='banktransactionmodel',
            name='to_bank_current_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
