# Generated by Django 3.2.25 on 2024-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_auto_20240516_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionmodel',
            name='from_bank_current_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banktransactionmodel',
            name='to_bank_current_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
