# Generated by Django 3.2.25 on 2024-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0003_auto_20240516_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionmodel',
            name='withdraw_or_deposit',
            field=models.CharField(blank=True, choices=[('withdraw', 'withdraw'), ('depos"deposit', 'deposit')], max_length=200, null=True),
        ),
    ]
