# Generated by Django 3.2.25 on 2024-05-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0004_banktransactionmodel_withdraw_or_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransactionmodel',
            name='withdraw_or_deposit',
        ),
    ]
